namespace Espeon {
    public enum LocalisationStringKey {
        PING_COMMAND,
        REMINDER_CREATED,
        REMINDER_PARSER_NO_TIMESPAN,
        REMINDER_PARSER_IN_THE_PAST,
        GUILDTAG_ALREADY_EXISTS,
        TAG_CREATED,
        TAG_DOESNT_EXIST,
        TAG_RESERVED_WORD,
        MUST_OWN_TAG,
        TAG_DELETED,
        MESSAGE_DOES_NOT_EXIST,
        INVALID_MESSAGE_ID_PATH,
        MESSAGE_HAS_EMPTY_CONTENT,
        MODULE_NOT_FOUND,
        NO_MATCHING_COMMANDS,
        NO_REMINDERS_FOUND,
        INVALID_PEPOWHATIF_SIZE
    }
}