// <auto-generated />
using Espeon.Databases.CommandStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using System.Collections.Generic;

namespace Espeon.Migrations.CommandStoreMigrations
{
    [DbContext(typeof(CommandStore))]
    [Migration("20190308221559_removedrespones")]
    partial class removedrespones
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.0.0-preview.18572.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Espeon.Databases.CommandInfo", b =>
                {
                    b.Property<string>("Name");

                    b.Property<string>("ModuleName");

                    b.Property<List<string>>("Aliases");

                    b.HasKey("Name", "ModuleName");

                    b.HasIndex("ModuleName");

                    b.ToTable("CommandInfo");
                });

            modelBuilder.Entity("Espeon.Databases.ModuleInfo", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<List<string>>("Aliases");

                    b.HasKey("Name");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Espeon.Databases.CommandInfo", b =>
                {
                    b.HasOne("Espeon.Databases.ModuleInfo", "Module")
                        .WithMany("Commands")
                        .HasForeignKey("ModuleName")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
